import { SCENE_RANGES } from './devScrollConfig';

export const ZOOM_CARD_EXIT_STAGGER = 0.006;
export const ZOOM_CARD_EXIT_DURATION = 0.018;
export const ZOOM_CARD_COUNT = 8;

export const CHAPTER4_ZOOM_END = SCENE_RANGES[3][1] + 0.036;
export const CHAPTER4_ZOOM_HOLD_END = CHAPTER4_ZOOM_END + 0.044;
export const CHAPTER4_ZOOM_BRIDGE_END =
    CHAPTER4_ZOOM_HOLD_END + (ZOOM_CARD_COUNT - 1) * ZOOM_CARD_EXIT_STAGGER + ZOOM_CARD_EXIT_DURATION;
export const CHAPTER4_ZOOM_COPY_EXIT_DURATION = 0.014;
export const CHAPTER4_ZOOM_SECTION_END = CHAPTER4_ZOOM_BRIDGE_END + CHAPTER4_ZOOM_COPY_EXIT_DURATION;
