export { Home } from './Home';
export { About } from './About';
export { News } from './News';
export { NewsDetail } from './NewsDetail';
export { AppShowcase } from './AppShowcase';
export { Board } from './Board';
export { BoardDetail } from './BoardDetail';
export { Contact } from './Contact';
export { Admin } from './Admin';
